import test from 'node:test';import assert from 'node:assert/strict';import{parseArgs,applyOptions}from'../src/cli.js';import{DEFAULT_SETTINGS}from'../src/config/settings.js';import{quickProfile,researchProfile}from'../src/menu/index.js';
test('parseArgs separates flags, values and positionals',()=>{const o=parseArgs(['--max','30','--no-tunnel','extra','--debug']);assert.equal(o.values.get('max'),'30');assert.ok(o.flags.has('no-tunnel'));assert.ok(o.flags.has('debug'));assert.deepEqual(o.positional,['extra']);});
test('parseArgs rejects options with a missing value',()=>{assert.throws(()=>parseArgs(['--max']),/Missing value/);assert.throws(()=>parseArgs(['--rounds','--debug']),/Missing value/);});
test('applyOptions overrides settings without mutating the source',()=>{const m=DEFAULT_SETTINGS.scan.maxCandidates,n=applyOptions(DEFAULT_SETTINGS,parseArgs(['--max','5','--tunnel-limit','2','--no-streaming']));assert.equal(n.scan.maxCandidates,5);assert.equal(n.tunnel.limit,2);assert.equal(n.streaming.enabled,false);assert.equal(DEFAULT_SETTINGS.scan.maxCandidates,m);});
test('applyOptions validates numeric input',()=>{assert.throws(()=>applyOptions(DEFAULT_SETTINGS,parseArgs(['--max','abc'])),/positive number/);assert.throws(()=>applyOptions(DEFAULT_SETTINGS,parseArgs(['--rounds','-2'])),/positive number/);});
test('debug flag and explicit xray path are honoured',()=>{const n=applyOptions(DEFAULT_SETTINGS,parseArgs(['--debug','--xray-path','/tmp/xray']));assert.equal(n.logging.level,'debug');assert.equal(n.tunnel.xrayPath,'/tmp/xray');});
test('lowest-variant flag is explicit and the abr alias remains compatible',()=>{assert.equal(applyOptions(DEFAULT_SETTINGS,parseArgs(['--lowest-variant'])).streaming.variantMode,'lowest');assert.equal(applyOptions(DEFAULT_SETTINGS,parseArgs(['--abr'])).streaming.variantMode,'lowest');});
test('quickProfile reduces the workload for a fast run',()=>{const q=quickProfile(DEFAULT_SETTINGS);assert.ok(q.scan.maxCandidates<DEFAULT_SETTINGS.scan.maxCandidates);assert.ok(q.tunnel.limit<DEFAULT_SETTINGS.tunnel.limit);assert.equal(q.tunnel.rounds,1);});
test('researchProfile restores the deep load budget',()=>{const r=researchProfile(DEFAULT_SETTINGS);assert.equal(r.load.durationMs,12000);assert.equal(r.load.maxDownloadBytes,24*1024*1024);assert.equal(r.load.flows,6);assert.equal(r.load.idleSamples,4);});
