import test from'node:test';import assert from'node:assert/strict';import{summarizeWindows,summarizeLatency,summarizeFanout,toGateMetrics,quantile,loadLatencyTimeout}from'../src/probe/load.js';import{evaluateGates,capScore,buildVerdict,SCORE_CAPS}from'../src/measurement/gates.js';import{summarizeLoad,scoreLoad,applyTunnelResults,rankCandidates}from'../src/report.js';import{createDefaultSettings,migrateSettings,estimateTrafficBytes,SETTINGS_VERSION}from'../src/config/settings.js';const MB=1024*1024;
test('single-flow windows preserve transfer history',()=>{const w=Array.from({length:6},()=>({bytes:2*MB,ms:1000,ok:true})),r=summarizeWindows(w);assert.equal(r.totalBytes,12*MB);assert.ok(r.sustainedMbps>16);assert.equal(r.shapingRatio,1);});
test('latency reports inflation, jitter and loss',()=>{const r=summarizeLatency({idle:[40,42,44,46],loaded:[120,130,140,600],attempts:10,failures:2});assert.equal(r.idleRttMs,43);assert.equal(r.loadedRttMs,135);assert.ok(r.jitterMs>200);assert.equal(r.lossRate,.2);});
test('quantile and fanout helpers are defensive',()=>{assert.equal(quantile([10,20],.5),15);assert.equal(quantile([],.5),null);assert.equal(summarizeFanout([{ok:true,ttfbMs:300},{ok:true,ttfbMs:500},{ok:false}],1000).fanoutSuccess,.6667);});
test('absolute gates fail a path that collapses under load',()=>{const r=evaluateGates(toGateMetrics({downlink:{sustainedMbps:18,shapingRatio:.2},latency:{rttIncreaseMs:810,rpm:66,rttInflation:6,jitterMs:300,lossRate:.15},fanout:{fanoutSuccess:.5,freshConnectionMs:2600},uplink:{sustainedMbps:.1}}));assert.equal(r.status,'fail');assert.ok(r.failures.includes('shapingRatio'));assert.equal(capScore(96.4,r),SCORE_CAPS.fail);assert.equal(buildVerdict({gateResult:r,cappedScore:45}).label,'unusable');});
test('healthy loaded path can pass',()=>{const r=evaluateGates({sustainedMbps:30,shapingRatio:.95,rpm:700,rttIncreaseMs:40,rttInflation:1.2,jitterMs:25,lossRate:0,fanoutSuccess:1,freshConnectionMs:350,uplinkMbps:4});assert.equal(r.status,'pass');assert.equal(capScore(88.2,r),88.2);});
test('load summary uses parallel throughput and RPM',()=>{const l=summarizeLoad([{ok:true,downlink:{sustainedMbps:24,perFlowMbps:4,shapingRatio:.88,totalBytes:12*MB,flows:6},latency:{rttIncreaseMs:40,rttInflation:1.3,rpm:300,jitterMs:30,lossRate:0},fanout:{fanoutSuccess:1,freshConnectionMs:420},uplink:{sustainedMbps:3,totalBytes:3*MB}}]);assert.equal(l.bytes,15*MB);assert.equal(l.flows,6);assert.ok(scoreLoad(l)>60);});
function base(ip){return{ip,range:'x',eligibility:{attempts:8,successes:8,successRate:1,confidence95:{lower:.68,upper:1},confidence:'medium',handshakeMedianMs:120,pops:{dominant:'FRA'},errors:{}}}}
test('measured partial ranks above eligibility-only and keeps capped score',()=>{const m=applyTunnelResults(base('94.156.10.199'),{browsing:[{score:82,bytes:2*MB}],streaming:[{score:null,error:'manifest_failed'}],load:[{ok:true,downlink:{sustainedMbps:37.84,shapingRatio:1.1,totalBytes:120*MB,flows:6},latency:{rttIncreaseMs:140,rttInflation:1.76,rpm:185,jitterMs:40,lossRate:0},fanout:{fanoutSuccess:1,freshConnectionMs:500},uplink:{sustainedMbps:null,totalBytes:0}}]},{browsing:true,streaming:true,load:true}),u=applyTunnelResults(base('8.34.146.168'),null,{browsing:true,streaming:true,load:true});assert.equal(m.measurement.status,'partial');assert.ok(Number.isFinite(m.scores.overall));assert.ok(m.scores.overall<=70);assert.equal(u.measurement.status,'unmeasured');assert.equal(rankCandidates([u,m])[0].ip,'94.156.10.199');});
test('old settings migrate to multi-megabyte load defaults',()=>{const m=migrateSettings({version:2,streaming:{maxSegments:10}},'linux');assert.equal(m.version,SETTINGS_VERSION);assert.equal(m.load.enabled,true);assert.ok(estimateTrafficBytes(createDefaultSettings('linux'))>30*MB);});
test('loaded-latency requests cannot extend a candidate by the full bulk timeout',()=>{assert.equal(loadLatencyTimeout(20000),3000);assert.equal(loadLatencyTimeout(1500),1500);});
