import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import os from'node:os';import path from'node:path';import{DEFAULT_SETTINGS,createDefaultSettings,mergeSettings,loadSettings,saveSettings,resolveWorkloads,loadCatalog}from'../src/config/settings.js';
test('mergeSettings merges nested objects without mutating defaults',()=>{const m=mergeSettings(DEFAULT_SETTINGS,{scan:{rounds:9}});assert.equal(m.scan.rounds,9);assert.equal(m.scan.maxCandidates,DEFAULT_SETTINGS.scan.maxCandidates);assert.equal(DEFAULT_SETTINGS.scan.rounds,3);});
test('Android defaults reduce contention and checkpoint more often',()=>{const a=createDefaultSettings('android'),d=createDefaultSettings('linux');assert.equal(a.scan.concurrency,6);assert.equal(d.scan.concurrency,12);assert.equal(a.hard.saveEvery,10);assert.equal(d.hard.saveEvery,25);assert.ok(a.calibration.levels.at(-1)<d.calibration.levels.at(-1));});
test('current settings ship bounded Full Scan defaults',()=>{assert.equal(DEFAULT_SETTINGS.version,6);assert.equal(DEFAULT_SETTINGS.verification.enabled,true);assert.equal(DEFAULT_SETTINGS.calibration.enabled,true);assert.equal(DEFAULT_SETTINGS.streaming.variantMode,'fixed');assert.equal(DEFAULT_SETTINGS.load.enabled,true);assert.equal(DEFAULT_SETTINGS.load.durationMs,8000);assert.equal(DEFAULT_SETTINGS.load.maxDownloadBytes,12*1024*1024);assert.equal(DEFAULT_SETTINGS.load.flows,4);assert.equal(DEFAULT_SETTINGS.load.timeoutMs,7000);assert.equal(DEFAULT_SETTINGS.load.idleSamples,2);});
test('loadSettings falls back to defaults for missing or broken files',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'cfqoe-set-')),f=path.join(d,'settings.json');assert.deepEqual(loadSettings(f).scan,DEFAULT_SETTINGS.scan);fs.writeFileSync(f,'{ not json');assert.deepEqual(loadSettings(f).scan,DEFAULT_SETTINGS.scan);});
test('saveSettings then loadSettings round trips',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'cfqoe-set-')),f=path.join(d,'settings.json');saveSettings(f,mergeSettings(DEFAULT_SETTINGS,{tunnel:{limit:11}}));assert.equal(loadSettings(f).tunnel.limit,11);});
test('version 1 settings files receive the new measurement defaults',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'cfqoe-set-')),f=path.join(d,'settings.json');fs.writeFileSync(f,JSON.stringify({version:1,hard:{saveEvery:7}}));const s=loadSettings(f);assert.equal(s.hard.saveEvery,7);assert.equal(s.verification.enabled,true);});
test('resolveWorkloads combines built-in selection with custom entries',()=>{const c=loadCatalog(new URL('../config/workloads.default.json',import.meta.url).pathname),s=mergeSettings(DEFAULT_SETTINGS,{browsing:{workloads:['cloudflare-docs']},customWorkloads:{browsing:[{name:'mine',pageUrl:'https://example.com/'}]}});assert.equal(resolveWorkloads({settings:s,catalog:c,kind:'browsing'}).length,2);});
test('default catalog entries are well formed',()=>{const c=loadCatalog(new URL('../config/workloads.default.json',import.meta.url).pathname);for(const i of c.browsing)new URL(i.pageUrl);for(const i of c.streaming)assert.match(i.manifestUrl,/\.m3u8$/);});
