import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { DEFAULT_SETTINGS, createDefaultSettings, mergeSettings, loadSettings, saveSettings, resolveWorkloads, loadCatalog } from '../src/config/settings.js';

test('mergeSettings merges nested objects without mutating defaults', () => { const merged = mergeSettings(DEFAULT_SETTINGS, { scan: { rounds: 9 } }); assert.equal(merged.scan.rounds, 9); assert.equal(merged.scan.maxCandidates, DEFAULT_SETTINGS.scan.maxCandidates); assert.equal(DEFAULT_SETTINGS.scan.rounds, 3); });
test('Android defaults reduce contention and checkpoint more often', () => { const android=createDefaultSettings('android'),desktop=createDefaultSettings('linux'); assert.equal(android.scan.concurrency,6); assert.equal(desktop.scan.concurrency,12); assert.equal(android.hard.concurrency,6); assert.equal(desktop.hard.concurrency,12); assert.equal(android.hard.saveEvery,10); assert.equal(desktop.hard.saveEvery,25); assert.ok(android.calibration.levels.at(-1)<desktop.calibration.levels.at(-1)); });
test('current settings ship verification, calibration, retry and enforced traffic caps', () => { assert.equal(DEFAULT_SETTINGS.version,6); assert.equal(DEFAULT_SETTINGS.verification.enabled,true); assert.equal(DEFAULT_SETTINGS.calibration.enabled,true); assert.equal(DEFAULT_SETTINGS.streaming.variantMode,'fixed'); assert.equal(DEFAULT_SETTINGS.streaming.researchSegments,6); assert.ok(DEFAULT_SETTINGS.streaming.maxBytes>0); assert.ok(DEFAULT_SETTINGS.browsing.maxBytes>0); assert.equal(DEFAULT_SETTINGS.load.enabled,true); });
test('loadSettings falls back to defaults for missing or broken files', () => { const directory=fs.mkdtempSync(path.join(os.tmpdir(),'cfqoe-set-')),file=path.join(directory,'settings.json'); assert.deepEqual(loadSettings(file).scan,DEFAULT_SETTINGS.scan); fs.writeFileSync(file,'{ not json'); assert.deepEqual(loadSettings(file).scan,DEFAULT_SETTINGS.scan); });
test('saveSettings then loadSettings round trips', () => { const directory=fs.mkdtempSync(path.join(os.tmpdir(),'cfqoe-set-')),file=path.join(directory,'settings.json'); saveSettings(file,mergeSettings(DEFAULT_SETTINGS,{tunnel:{limit:11}})); assert.equal(loadSettings(file).tunnel.limit,11); });
test('version 1 settings files receive the new measurement defaults', () => { const directory=fs.mkdtempSync(path.join(os.tmpdir(),'cfqoe-set-')),file=path.join(directory,'settings.json'); fs.writeFileSync(file,JSON.stringify({version:1,hard:{saveEvery:7}})); const settings=loadSettings(file); assert.equal(settings.hard.saveEvery,7); assert.equal(settings.hard.screeningRounds,1); assert.equal(settings.verification.enabled,true); });
test('resolveWorkloads combines built-in selection with custom entries', () => { const catalog=loadCatalog(new URL('../config/workloads.default.json',import.meta.url).pathname); const settings=mergeSettings(DEFAULT_SETTINGS,{browsing:{workloads:['cloudflare-docs']},customWorkloads:{browsing:[{name:'mine',pageUrl:'https://example.com/'}]}}); assert.equal(resolveWorkloads({settings,catalog,kind:'browsing'}).length,2); });
